export const extensionList = {
  image: new Set(['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']),
  video: new Set(['mp4', 'webm', 'ogg']),
  audio: new Set(['mp3', 'ogg', 'wav', 'webm']),
  pdf: new Set(['pdf']),
  doc: new Set(['doc', 'docx']),
  xls: new Set(['xls', 'xlsx']),
  ppt: new Set(['ppt', 'pptx']),
  zip: new Set(['zip']),
  rar: new Set(['rar']),
  tar: new Set(['tar']),
  '7z': new Set(['7z']),
  txt: new Set(['txt']),
  csv: new Set(['csv']),
  rtf: new Set(['rtf']),
  html: new Set(['html']),
  xml: new Set(['xml']),
  json: new Set(['json']),
};
